"use client";
import { useEffect, useState } from "react";
import { Alert, Button, Field, Input, StatusBadge } from "@openhiggsfield/design";
import { api } from "@/projects/api";
import { useSession } from "@/shell/workspace-shell";
import type { User } from "@/service/auth";
import type { Job } from "@/projects/types";
export const ACCOUNT_SECTIONS={
  activity:{title:"생성 내역",description:"진행 상황과 결과, 사용한 크레딧을 확인하세요."},
  credits:{title:"크레딧",description:"사용 가능한 잔액과 지급·사용·환불 내역을 확인하세요."},
  profile:{title:"계정 정보",description:"현재 로그인한 계정의 정보를 확인하세요."},
  notifications:{title:"알림 설정",description:"제작 흐름에 맞는 알림을 준비하고 있습니다."},
  billing:{title:"결제 및 구독",description:"크레딧 구매와 결제 수단을 관리할 공간입니다."},
};
type Ledger={id:string;amount:number;kind:string;description:string;created_at:string};
const states:Record<Job["state"],string>={submitting:"접수 중",pending:"생성 중",completed:"완료",failed:"실패 · 환불",unknown:"접수 확인 필요"};
export function AccountPage({section,user:initialUser}:{section:keyof typeof ACCOUNT_SECTIONS;user:User}){
  const session=useSession(),user=session.user || initialUser,meta=ACCOUNT_SECTIONS[section];
  const [rows,setRows]=useState<Ledger[]>([]),[jobs,setJobs]=useState<Job[]>([]),[balance,setBalance]=useState(user.credits),[error,setError]=useState(""),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0),[filter,setFilter]=useState("");
  const preview=section==="notifications" || section==="billing";
  useEffect(()=>{
    if(section!=="credits" && section!=="activity")return;
    const controller=new AbortController();setLoading(true);setError("");
    const work=section==="credits"?api<{ledger:Ledger[];balance:number}>("credits",{signal:controller.signal}).then(r=>{setRows(r.ledger);setBalance(r.balance);}):api<Job[]>("jobs",{signal:controller.signal}).then(setJobs);
    void work.catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();
  },[section,revision]);
  return <main className="ws-page ws-account-panel"><div className="ws-page-heading"><div><span className="ws-eyebrow">MY PAGE / {section.toUpperCase()}</span><h1>{meta.title}</h1><p>{meta.description}</p></div>{!preview && section!=="profile" && <Button disabled={loading} onClick={()=>{setRevision(n=>n+1);void session.refresh();}}>새로고침</Button>}{preview && <StatusBadge tone="warning">준비 중 · 디자인 미리보기</StatusBadge>}</div>
    {error && <Alert>{error}</Alert>}
    {section==="credits" && <><div className="ws-account-summary"><section className="ws-card"><span className="ws-eyebrow">AVAILABLE CREDITS</span><strong className="ws-balance">{balance.toLocaleString()} <small>◇</small></strong><p className="ws-muted">생성 전에 크레딧을 예약하고, 실패하면 돌려드립니다.</p><Button href="/" variant="primary">스튜디오에서 사용하기 ↗</Button></section><section className="ws-card"><h2>크레딧이 더 필요한가요?</h2><p className="ws-muted">신규 계정에는 기본 50 크레딧을 지급합니다. 동영상 생성은 잔액 51 이상이고 생성 비용을 충당할 수 있을 때 이용할 수 있습니다. 추가 크레딧은 관리자가 지급합니다. 필요한 수량과 사용 목적을 관리자에게 전달해 주세요.</p>{user.admin?<Button href="/admin/credits">크레딧 관리</Button>:<StatusBadge>관리자 지급 방식</StatusBadge>}<Button href="/account/billing">결제 기능 미리보기</Button></section></div><section className="ws-card"><div className="ws-settings-heading"><h2>크레딧 사용 내역</h2><span className="ws-muted">최근 100건</span></div>{loading?<p role="status">내역을 불러오는 중…</p>:rows.length===0?<p className="ws-muted">아직 기록된 내역이 없습니다.</p>:<div className="ws-table-scroll"><table className="ws-admin-table"><thead><tr><th>일시</th><th>내역</th><th>증감</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(Number(r.created_at)).toLocaleString("ko-KR")}</td><td>{r.description}</td><td className={r.amount>0?"ws-credit-positive":""}>{r.amount>0?"+":""}{r.amount.toLocaleString()}</td></tr>)}</tbody></table></div>}</section></>}
    {section==="activity" && <><div className="ws-account-activity-toolbar"><Field label="생성 상태" htmlFor="account-job-state"><select id="account-job-state" className="ws-select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">전체 상태</option>{Object.entries(states).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Button href="/account">완성된 에셋 보기 ↗</Button></div><section className="ws-card"><div className="ws-settings-heading"><h2>요청 내역</h2><span className="ws-muted">최근 100건</span></div><p className="ws-muted">접수 확인이 필요한 요청은 자동 재시도하지 않습니다. 요청 ID를 관리자에게 전달해 주세요.</p>{loading?<p role="status">생성 내역을 불러오는 중…</p>:jobs.filter(j=>!filter || j.state===filter).length===0?<div className="ws-account-empty"><h3>표시할 생성 요청이 없습니다</h3><p className="ws-muted">다른 상태를 선택하거나 스튜디오에서 새로운 작업을 시작하세요.</p><Button href="/">스튜디오 열기</Button></div>:<div className="ws-account-job-list">{jobs.filter(j=>!filter || j.state===filter).map(j=><article key={j.id}><div><StatusBadge tone={j.state==="completed"?"success":j.state==="failed"?"danger":"warning"}>{states[j.state]}</StatusBadge><time>{new Date(Number(j.created_at)).toLocaleString("ko-KR")}</time></div><p>{j.request_id || j.id}</p><div><span>{j.cost} 크레딧</span>{j.project_id && <Button href={`/projects/${j.project_id}`} size="sm">프로젝트 보기</Button>}</div></article>)}</div>}</section></>}
    {section==="profile" && <><section className="ws-card"><div className="ws-account-profile-head"><span className="ws-account-avatar" aria-hidden>{user.name.slice(0,1)}</span><div><h2>{user.name}</h2><p className="ws-muted">{user.admin?"관리자 계정":"개인 계정"}</p></div></div><dl className="ws-account-facts"><div><dt>아이디</dt><dd>{user.username || "이메일로 로그인"}</dd></div><div><dt>이메일</dt><dd>{user.email}</dd></div><div><dt>이름</dt><dd>{user.name}</dd></div></dl></section><section className="ws-card"><div className="ws-settings-heading"><h2>프로필과 보안 관리</h2><StatusBadge tone="warning">준비 중 · 디자인 미리보기</StatusBadge></div><p className="ws-muted">프로필 수정, 이메일 인증, 비밀번호 변경은 아직 제공하지 않습니다.</p><fieldset disabled className="ws-account-disabled-fields"><Field label="표시 이름" htmlFor="preview-name"><Input id="preview-name" value={user.name} readOnly/></Field><div className="ws-settings-actions"><Button disabled>이름 변경</Button><Button disabled>이메일 인증</Button><Button disabled>비밀번호 변경</Button></div></fieldset></section></>}
    {preview && <><div className="ws-account-preview-note"><span aria-hidden>◌</span><div><strong>곧 만날 새로운 기능</strong><p>아래는 화면 구성 미리보기입니다. 설정은 저장되지 않으며 결제나 알림 발송이 이루어지지 않습니다.</p></div></div>{section==="notifications"?<section className="ws-card"><h2>받고 싶은 알림</h2><p className="ws-muted">아래 선택 상태는 디자인 예시입니다.</p>{[{title:"생성 완료",description:"이미지와 영상이 완성되면 알려드립니다.",on:true},{title:"생성 실패와 환불",description:"문제가 발생한 요청과 크레딧 환불을 안내합니다.",on:true},{title:"크레딧 부족",description:"다음 작업을 시작하기 전에 잔액을 알려드립니다.",on:false}].map(item=><label className="ws-account-toggle-row" key={item.title}><span><strong>{item.title}</strong><small>{item.description}</small></span><input type="checkbox" role="switch" aria-label={item.title} checked={item.on} disabled readOnly/></label>)}<div className="ws-settings-actions"><StatusBadge>이메일 · 준비 중</StatusBadge><StatusBadge>앱 내 알림 · 준비 중</StatusBadge></div><Button disabled>알림 설정 저장</Button></section>:<><div className="ws-account-summary"><section className="ws-card ws-account-billing-preview"><span className="ws-eyebrow">CREDIT PURCHASE / PREVIEW</span><h2>필요한 만큼, 크레딧 충전</h2><p className="ws-muted">가격과 충전 단위는 추후 안내합니다. 현재는 관리자에게 지급을 요청하세요.</p><div className="ws-account-preview-amount">— <small>크레딧</small></div><Button disabled>크레딧 구매 · 준비 중</Button></section><section className="ws-card"><span className="ws-eyebrow">PAYMENT METHOD / PREVIEW</span><h2>결제 수단</h2><div className="ws-account-payment-placeholder"><span aria-hidden>＋</span><p>카드 등록 화면이 여기에 표시됩니다</p></div><Button disabled>결제 수단 추가</Button></section></div><section className="ws-card"><h2>구독 및 결제 내역</h2><p className="ws-muted">향후 이용 플랜, 청구일, 영수증을 이곳에서 확인할 수 있습니다. 현재 구독 상품과 온라인 결제는 제공하지 않습니다.</p><div className="ws-account-preview-receipt"><span>결제일</span><span>이용 내역</span><span>금액</span></div><p className="ws-muted">결제 기능 연결 후 실제 내역이 표시됩니다.</p><Button disabled>영수증 관리</Button></section></>}</>}
  </main>;
}
