"use client";
import { AgentThinking, AgentReviewPanel } from "./agent-thinking";
import { useCallback, useEffect, useRef, useState } from "react";
import { Alert, Button, Field, Input, Segment, Textarea } from "@openhiggsfield/design";
import { ProductImageUpload } from "./product-image-upload";
import { ReelImageRecommendation } from "./reel-image-recommendation";
import type { ProductImage } from "@/projects/product-detail";
import { api } from "@/projects/api";
import { reelSourceImageId, reelIssues, reelTerminal, reelTimeline, type ReelWorkflow, type ReelScene } from "@/projects/reel-workflow";
import { createReelOverlays } from "@/render/reel-overlays";
import "./reel-workflow.css";
const assetUrl = (id: string) => `/api/workspace/assets/${id}`;
const time = (seconds: number) => `${Math.floor(seconds / 60).toString().padStart(2, "0")}:${Math.floor(seconds % 60).toString().padStart(2, "0")}`;
type Asset = { id: string; name: string; mime: string; url: string };
const roleLabel = (role: string) => ({ hook: "도입", development: "전개", change: "변화", closing: "마무리", solution: "해결", cta: "마무리" } as Record<string, string>)[role] || role;
const statusLabel = { pending: "다음 작업 준비", running: "AI 작업 중", waiting_user: "선택을 기다려요", waiting_tool: "제작 중", ready: "함께 다듬어요", paused_budget: "확인 필요", failed: "작업 종료", cancelled: "중단됨", completed: "파일 준비 완료" };
export function ReelWorkflowCreator({ active, onWorkspaceChange, onBusyChange }: { active: boolean; onWorkspaceChange: (value: boolean) => void; onBusyChange: (value: boolean) => void }) {
  const [run, setRun] = useState<ReelWorkflow | null>(null), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(""), [phase, setPhase] = useState("");
  const [referenceImages, setReferenceImages] = useState<ProductImage[]>([]), [uploading, setUploading] = useState(false), [recommending, setRecommending] = useState(false);
  const [idea, setIdea] = useState(""), [duration, setDuration] = useState("30"), [narration, setNarration] = useState(false), [voice, setVoice] = useState("coral"), [available, setAvailable] = useState(false);
  const [selected, setSelected] = useState(""), [draft, setDraft] = useState<ReelScene | null>(null), [feedback, setFeedback] = useState(""), [purpose, setPurpose] = useState("branding"), [quote, setQuote] = useState({ image: 4, video: 48, voice: 2 });
  const [quoteKey, setQuoteKey] = useState("");
  const [assets, setAssets] = useState<Asset[]>([]), [library, setLibrary] = useState(false), [safeZone, setSafeZone] = useState(false), [muted, setMuted] = useState(false), [position, setPosition] = useState(0), [watched, setWatched] = useState(false), [listened, setListened] = useState(false), [mutedChecked, setMutedChecked] = useState(false), [sampleWatched, setSampleWatched] = useState(false), [allowDuration, setAllowDuration] = useState(false);
  const current = useRef(run), inFlight = useRef(false), video = useRef<HTMLVideoElement>(null); current.current = run;
  const accept = useCallback((next: ReelWorkflow) => { setRun(old => old?.id === next.id && old.revision > next.revision ? old : next); }, []);
  useEffect(() => { let gone = false; const id = new URLSearchParams(window.location.search).get("reelWorkflow"); Promise.all([id ? api<ReelWorkflow>(`reel-workflow/${id}`) : api<{ run: ReelWorkflow | null }>("reel-workflow").then(v => v.run), api<{ quickCardReady: boolean }>("session")]).then(([r, s]) => { if (!gone) { setRun(r); setAvailable(s.quickCardReady); } }).catch(e => !gone && setError(e.message)).finally(() => !gone && setLoading(false)); return () => { gone = true; }; }, []);
  useEffect(() => { onWorkspaceChange(!!run); onBusyChange(busy || uploading || recommending); }, [!!run, busy, uploading, recommending, onWorkspaceChange, onBusyChange]);
  useEffect(() => { if (run) { const url = new URL(window.location.href); url.searchParams.set("reelWorkflow", run.id); window.history.replaceState(null, "", url); if (!run.scenes.some(s => s.id === selected)) setSelected(run.scenes[0]?.id || ""); } }, [run?.id, run?.scenes.length, selected]);
  useEffect(() => { setDraft(run?.scenes.find(s => s.id === selected) || null); }, [selected, run?.contentVersion]);
  useEffect(() => { let gone = false; if (run && selected) { const key = `${run.id}:${selected}:${run.contentVersion}`; api<typeof quote>(`reel-workflow/${run.id}/quote?sceneId=${encodeURIComponent(selected)}`).then(value => { if (!gone) { setQuote(value); setQuoteKey(key); } }).catch(() => { if (!gone) setError("생성 비용을 확인하지 못했어요. 장면을 다시 선택하거나 새로고침해 주세요."); }); } return () => { gone = true; }; }, [run?.id, selected, run?.contentVersion]);
  useEffect(() => { setWatched(false); setListened(false); setMutedChecked(false); setSampleWatched(false); }, [run?.contentVersion, run?.output?.id, run?.sample?.id]);
  const call = useCallback(async (data: Record<string, unknown>) => {
    const r = current.current; if (!r) return;
    setBusy(true); setError("");
    try { const next = await api<ReelWorkflow>(`reel-workflow/${r.id}`, { method: "POST", body: JSON.stringify({ revision: r.revision, responseId: crypto.randomUUID(), ...data }) }); accept(next); return next; }
    catch (e) { setError((e as Error).message); const latest = await api<ReelWorkflow>(`reel-workflow/${r.id}`).catch(() => null); if (latest) accept(latest); }
    finally { setBusy(false); }
  }, [accept]);
  useEffect(() => {
    if (!active || !run || reelTerminal(run)) return;
    const tick = async () => {
      const r = current.current; if (!r || inFlight.current) return;
      if (r.status === "pending" && !busy) { inFlight.current = true; try { await call({ action: "step" }); } finally { inFlight.current = false; } }
      else if (["running", "waiting_tool"].includes(r.status)) {
        inFlight.current = true;
        try { const polling = r.status === "waiting_tool" && r.task && ["image", "video"].includes(r.task.kind); const next = await api<ReelWorkflow>(`reel-workflow/${r.id}`, polling ? { method: "POST", body: JSON.stringify({ action: "visual_status" }) } : undefined); accept(next); } catch (e) { setError((e as Error).message); } finally { inFlight.current = false; }
      }
    };
    // A pending provider response can keep the same revision; keep checking it.
    const timer = setInterval(tick, run.status === "pending" ? 300 : 3000); return () => clearInterval(timer);
  }, [active, run?.revision, busy, call, accept]);
  // Long render/voice requests do not prevent observing saved progress in another request.
  useEffect(() => { if (!active || !run || reelTerminal(run)) return; const timer = setInterval(() => { const r = current.current; if (r && (busy || ["running", "waiting_tool"].includes(r.status))) api<ReelWorkflow>(`reel-workflow/${r.id}`).then(accept).catch(() => {}); }, 3500); return () => clearInterval(timer); }, [active, run?.id, busy, accept]);
  async function start(sourceRunId?: string) { if (busy || uploading || recommending) return; setBusy(true); setError(""); try { const r = await api<ReelWorkflow>("reel-workflow", { method: "POST", body: JSON.stringify({ idea, referenceImageIds: referenceImages.map(image => image.id), duration: Number(duration), narration, voice, sourceRunId, key: crypto.randomUUID() }) }); setRun(r); setSelected(r.scenes[0]?.id || ""); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function upload(file: File, music = false) { setBusy(true); setError(""); try { const body = new FormData(); body.set("file", file); const asset = await api<Asset>("assets", { method: "POST", body }); await call(music ? { action: "music", assetId: asset.id } : { action: "attach", assetId: asset.id, sceneId: selected }); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function render(kind: "sample" | "full") {
    if (!run) return; setBusy(true); setError(""); setPhase("한글 글꼴과 문구 배치를 확인하고 있어요");
    try { const blob = await createReelOverlays(run, kind, setPhase), body = new FormData(); body.set("file", new File([blob], "reel-overlays.zip", { type: "application/zip" })); const asset = await api<{ url: string }>("exports", { method: "POST", body }); setPhase("서버에서 MP4를 합성하고 있어요"); await call({ action: "render", kind, overlayAssetId: asset.url.split("/").pop() }); }
    catch (e) { setError((e as Error).message); } finally { setBusy(false); setPhase(""); }
  }
  if (loading) return <AgentThinking stage="restore" />;
  if (!run) return <div className="rf-entry">
    <div className="rf-entry-copy"><span className="ws-eyebrow">FROM PHOTOS TO A REEL</span><h2>사진 속 이야기를,<br />움직이는 컷으로.</h2><p>사진 한 장도, 여러 장도 좋아요. AI가 사진을 읽고 프롬프트와 컷을 제안합니다. 원본과 움직임을 확인한 뒤 영상으로 만들어 보세요.</p><ProductImageUpload purpose="reel" images={referenceImages} onChange={setReferenceImages} disabled={busy || recommending} onBusyChange={setUploading} /><p className="rf-image-flow">사진 → 프롬프트·컷 승인 → 영상 제작</p></div>
    <form className="ws-card ws-form" onSubmit={e => { e.preventDefault(); void start(); }}><ReelImageRecommendation key={`${referenceImages.map(image => image.id).join(",")}:${duration}:${narration}`} images={referenceImages} idea={idea} duration={Number(duration)} narration={narration} available={available} disabled={busy || uploading} onBusyChange={setRecommending} onApply={setIdea} /><Field label="어떤 숏폼을 만들고 싶으세요?" htmlFor="reel-idea"><Textarea id="reel-idea" required={!referenceImages.length} disabled={busy} minLength={2} maxLength={3000} rows={6} value={idea} onChange={e => setIdea(e.target.value)} placeholder="예: 책상 위에 식물 하나 두고 싶어지는 30초 릴스. 잔잔한 분위기로, 가격과 구매 안내는 빼 주세요." /></Field><Field label="목표 길이"><Segment aria-label="숏폼 목표 길이" plate value={duration} onChange={v => { if (!busy && !recommending) setDuration(v); }} items={[15, 30, 60].map(n => ({ id: String(n), label: `${n}초` }))} /></Field><Field label="어떻게 전달할까요?"><Segment aria-label="숏폼 음성 방식" plate value={narration ? "voice" : "text"} onChange={v => { if (!busy && !recommending) setNarration(v === "voice"); }} items={[{ id: "text", label: "화면 문구 중심" }, { id: "voice", label: "AI 내레이션" }]} /></Field>{narration && <Field label="AI 목소리" htmlFor="reel-voice"><select id="reel-voice" value={voice} onChange={e => setVoice(e.target.value)}><option value="coral">Coral</option><option value="sage">Sage</option><option value="cedar">Cedar</option></select></Field>}<p className="ws-muted">대본 1 크레딧 · 이미지·영상·음성은 샘플에서 비용을 확인하고 선택합니다. 보유한 에셋으로도 제작할 수 있어요.</p>{error && <Alert>{error}</Alert>}{busy && <AgentThinking stage="start" />}<Button variant="primary" size="lg" type="submit" loading={busy} disabled={!available || uploading || recommending}>{referenceImages.length ? "사진으로 컷 만들기" : "AI와 대본 만들기"} · 1 크레딧</Button>{!available && <p className="ws-muted">관리자가 OpenAI API를 연결하면 시작할 수 있어요.</p>}</form>
  </div>;
  const timeline = reelTimeline(run.scenes), scene = run.scenes.find(s => s.id === selected), locked = busy || ["running", "waiting_tool", "pending"].includes(run.status), done = reelTerminal(run), view = run.output?.version === run.contentVersion ? run.output : run.sample?.version === run.contentVersion ? run.sample : undefined, issues = reelIssues(run), failedQuality = run.quality?.issues.some(i => i.severity === "error"), currentQuality = run.quality?.version === run.contentVersion && run.quality.renderId === run.output?.id;
  const activeTask = run.status === "waiting_tool" && run.task && !["completed", "failed", "discarded"].includes(run.task.state) ? run.task : undefined;
  const thinkingStage = activeTask ? activeTask.kind : phase ? "render" : run.stage === "production" && run.status === "running" ? "quality" : ["pending", "running"].includes(run.status) ? run.stage : "save";
  const quoteReady = quoteKey === `${run.id}:${selected}:${run.contentVersion}`;
  const change = (value: Partial<ReelScene>) => setDraft(d => d ? { ...d, ...value } : d);
  return <section className="rf-workspace" aria-label="AI와 함께 숏폼 제작">
    <header className="rf-bar"><div><span className="ws-eyebrow">REEL WORKSPACE</span><h2>{run.project.title}</h2></div><span className="rf-status" role="status">{statusLabel[run.status]}</span>{!done && <Button size="sm" onClick={() => void call({ action: "cancel" })}>제작 중단</Button>}</header>
    <div className="rf-spec"><span>{run.spec.duration}초{run.spec.durationLocked ? " · 길이 보호" : " · 변경 허용"}</span><span>9:16 · 30fps</span><span>{run.spec.narration ? `AI 음성 · ${run.spec.voice}` : "화면 문구 중심"}</span><span>{({ branding: "분위기·브랜드 기억", educate: "정보·저장", conversion: "상품 관심" } as Record<string, string>)[run.spec.purpose] || run.spec.purpose || "목적 확인 중"} · {run.spec.purposeOrigin === "user_explicit" ? "입력한 조건" : run.spec.purposeOrigin === "user_confirmed" ? "확정" : "추천"}</span></div>
    {(error || run.error) && <Alert>{error || run.error}</Alert>}
    {(phase || locked) && <AgentThinking key={`${run.stage}:${run.budget.calls}:${run.task?.key || ""}:${phase}`} stage={thinkingStage} queued={run.status === "pending"} turn={["pending", "running"].includes(run.status) ? run.budget.calls + (run.status === "pending" ? 1 : 0) : undefined} startedAt={activeTask ? activeTask.startedAt : run.status === "running" ? run.events.at(-1)?.at : undefined} detail={activeTask?.renderStep || phase || undefined} events={run.events} />}
    <AgentReviewPanel loop={run.editorial} />
    {run.question?.kind === "plan" && !!run.referenceImages?.length && <section className="rf-photo-storyboard" aria-label="사진 기반 컷 구성"><div className="rf-section-heading"><h3>사진에서 이어지는 {run.scenes.length}개의 컷</h3><span>컷을 선택해 원본·프롬프트를 수정한 뒤 대본을 승인하세요.</span></div><div className="rf-photo-cuts">{run.scenes.map((s, i) => <button type="button" key={s.id} aria-pressed={selected === s.id} onClick={() => setSelected(s.id)}>{s.sourceImageId ? <img src={assetUrl(s.sourceImageId)} alt={`${i + 1}번 컷 원본`} /> : <span className="rf-cut-no-source">연결한 영상</span>}<div><small>CUT {String(i + 1).padStart(2, "0")} · {s.frames / 30}초</small><strong>{s.title}</strong><p>{s.prompt}</p></div></button>)}</div></section>}
    <div className="rf-columns">
      <aside className="rf-conversation"><h3>함께 만드는 과정</h3><div className="rf-events" aria-live="polite">{run.events.slice(-6).map(e => <article key={e.id}><small>{new Date(e.at).toLocaleTimeString("ko-KR", { hour: "2-digit", minute: "2-digit" })}</small><strong>{e.title}</strong><p>{e.message}</p></article>)}</div>
        {run.question?.kind === "purpose" && <div className="rf-question"><h3>{run.question.text}</h3><select aria-label="숏폼 제작 목적" value={purpose} onChange={e => setPurpose(e.target.value)}><option value="branding">분위기와 브랜드 기억하기</option><option value="educate">저장하고 다시 보기</option><option value="conversion">상품 더 알아보기</option></select><Input aria-label="목적 직접 입력" placeholder="또는 원하는 반응을 직접 적어 주세요" onChange={e => e.target.value && setPurpose(e.target.value)} /><Button variant="primary" disabled={locked} onClick={() => void call({ action: "answer", requestId: run.question!.id, value: purpose })}>이 방향으로 진행</Button></div>}
        {run.question?.kind === "research" && <div className="rf-question"><p>{run.question.text}</p><Button disabled={locked} onClick={() => void call({ action: "answer", requestId: run.question!.id, value: "retry" })}>근거 다시 조사</Button><Button disabled={locked} onClick={() => void call({ action: "answer", requestId: run.question!.id, value: "creative" })}>효능·수치 없이 연출 중심으로</Button></div>}
        {run.question?.kind === "plan" && <div className="rf-question"><h3>대본과 콘티가 준비됐어요</h3><p>{run.question.text}</p><Button variant="primary" disabled={locked} onClick={() => void call({ action: "answer", requestId: run.question!.id })}>대본 승인 · 샘플로 진행</Button><Textarea aria-label="대본 전체 수정 의견" rows={3} value={feedback} onChange={e => setFeedback(e.target.value)} placeholder="전체 흐름에서 바꾸고 싶은 점" /><Button disabled={locked || feedback.length < 2} onClick={() => void call({ action: "revise_plan", feedback })}>대본 의견 반영</Button></div>}
        {run.status === "paused_budget" && <Button variant="primary" disabled={busy || run.budget.calls >= run.budget.maxCalls} onClick={() => void call({ action: "retry" })}>저장한 결과에서 재시도</Button>}
        {!!run.sources.length && <details><summary>확인한 출처 {run.sources.length}개</summary>{run.sources.map(s => <p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a><small>{s.claim}</small></p>)}</details>}
        <details><summary>제작 조건과 사용량</summary>{run.spec.constraints.map((v, i) => <p key={i}>{v}</p>)}<p>대본·검수 {run.budget.calls}/{run.budget.maxCalls}회 · 자산 {run.budget.generations}/{run.budget.maxGenerations}회 · 음성 {run.budget.voiceCalls}/{run.budget.maxVoiceCalls}회</p><p>음성은 AI로 생성됩니다. 원본 영상의 소리는 제외하고 내레이션·음악을 별도로 합성합니다.</p></details>
      </aside>
      <div className="rf-preview"><div className="rf-player-label"><span>{view ? view.kind === "sample" ? "실제 샘플 MP4" : "실제 전체 MP4" : "장면 콘티"}</span><small>1080 × 1920</small></div><div className="rf-player">
        {view ? <video key={view.id} ref={video} src={assetUrl(view.assetId)} poster={assetUrl(view.coverId)} controls playsInline muted={muted} onTimeUpdate={e => setPosition(e.currentTarget.currentTime)} onEnded={() => view.kind === "sample" ? setSampleWatched(true) : setWatched(true)} /> : <div className="rf-story-frame">{scene?.asset ? scene.asset.kind === "image" ? <img src={assetUrl(scene.asset.id)} alt={scene.title} style={{ objectPosition: `center ${scene.crop}%`, transform: `scale(${(scene.zoom || 100) / 100})`, transformOrigin: `center ${scene.crop}%` }} /> : <video src={assetUrl(scene.asset.id)} controls muted playsInline /> : <div className="rf-frame-empty"><span>{scene ? roleLabel(scene.role) : "YOUR NEXT REEL"}</span><p>{scene ? "이미지나 영상을 채우면\n장면이 움직이기 시작해요" : "대본과 장면을 준비하고 있어요"}</p></div>}<div className={`rf-frame-copy rf-frame-copy--${scene?.textPosition || "lower"}`}><strong>{scene?.title}</strong><p>{scene?.screenText}</p></div></div>}
        {safeZone && <div className="rf-safe-zone"><span>서비스 안전영역 예시<br />게시 앱에서 최종 확인</span></div>}
      </div><div className="rf-player-tools"><button type="button" aria-pressed={muted} onClick={() => setMuted(v => !v)}>{muted ? "소리 켜기" : "무음 보기"}</button><button type="button" aria-pressed={safeZone} onClick={() => setSafeZone(v => !v)}>안전영역</button><span>{time(position)} / {time(view?.duration || run.spec.duration)}</span></div>
        {run.planApproved && !done && <div className="rf-render-actions">{!run.sampleApproved ? <><Button variant="primary" disabled={locked || reelIssues(run, [run.scenes[0]?.id]).some(i => i.severity === "error")} onClick={() => void render("sample")}>대표 샘플 MP4 만들기</Button>{run.sample?.version === run.contentVersion && <><label><input type="checkbox" checked={sampleWatched} onChange={e => setSampleWatched(e.target.checked)} /> 샘플의 문구·움직임{run.spec.narration ? "·목소리를" : "을"} 확인했어요</label><Button variant="primary" disabled={locked || !sampleWatched} onClick={() => void call({ action: "approve_sample", watched: sampleWatched })}>샘플 승인 · 나머지 장면 제작</Button></>}</> : <><Button variant="primary" disabled={locked || issues.some(i => i.severity === "error")} onClick={() => void render("full")}>전체 MP4 {run.output ? "다시 합성" : "만들기"}</Button><p>원본 자산을 재사용합니다. 별도 생성 크레딧 없음.</p></>}</div>}
      </div>
      <aside className="rf-inspector">{scene && draft ? <><div className="rf-inspector-heading"><h3>{roleLabel(scene.role) || "장면"}</h3><small>v{scene.version} · {(scene.frames / 30).toFixed(1)}초</small></div><fieldset disabled={locked || done}>
        <label className="rf-check"><input type="checkbox" checked={!draft.copyLocked} onChange={e => change({ copyLocked: !e.target.checked })} /> 이 장면 문구 변경 허용</label>
        <Field label="화면 제목" htmlFor="rf-title"><Input id="rf-title" value={draft.title} disabled={draft.copyLocked} maxLength={90} onChange={e => change({ title: e.target.value })} /></Field><Field label="화면 설명" htmlFor="rf-screen"><Textarea id="rf-screen" value={draft.screenText} disabled={draft.copyLocked} maxLength={140} rows={2} onChange={e => change({ screenText: e.target.value })} /></Field>
        {run.spec.narration && <Field label="발화 대본 · 화면 설명과 별도" htmlFor="rf-narration"><Textarea id="rf-narration" value={draft.narration} disabled={draft.copyLocked} maxLength={200} rows={3} onChange={e => change({ narration: e.target.value })} /></Field>}
        <Field label="글자 배치"><Segment aria-label="숏폼 글자 배치" plate value={draft.textPosition} onChange={v => change({ textPosition: v as ReelScene["textPosition"] })} items={[{ id: "lower", label: "아래쪽" }, { id: "middle", label: "중앙" }]} /></Field>{run.spec.narration && <Field label="발화 자막"><Segment aria-label="발화 자막 스타일" plate value={draft.subtitleStyle} onChange={v => change({ subtitleStyle: v as ReelScene["subtitleStyle"] })} items={[{ id: "calm", label: "차분하게" }, { id: "emphasis", label: "크게 강조" }]} /></Field>}
        <details open={!!run.referenceImages?.length}><summary>컷 프롬프트·시간·사진 위치</summary><label>사진 확대 {draft.zoom || 100}%<input aria-label="사진 확대" type="range" min="100" max="150" value={draft.zoom || 100} onChange={e => change({ zoom: Number(e.target.value) })} /></label><Textarea aria-label="장면 이미지 영상 구상" rows={4} maxLength={1000} value={draft.prompt} onChange={e => change({ prompt: e.target.value })} /><label>사진 위치 <input aria-label="숏폼 사진 위치" type="range" min={0} max={100} value={draft.crop} onChange={e => change({ crop: Number(e.target.value) })} /></label><label><input type="checkbox" checked={allowDuration} onChange={e => setAllowDuration(e.target.checked)} /> 잠긴 길이 변경 허용</label><Input aria-label="숏폼 장면 초" type="number" min={1} max={15} step={.1} disabled={!allowDuration} value={draft.frames / 30} onChange={e => change({ frames: Math.round(Number(e.target.value) * 30) })} /></details>
        <Button disabled={locked || done} onClick={() => void call({ action: "edit_scene", sceneId: selected, scene: { ...draft, seconds: draft.frames / 30 }, allowDuration })}>이 장면 설정 저장</Button>
      </fieldset>
      <div className="rf-media-section"><h4>장면 자산</h4>{!!run.referenceImages?.length && <Field label="이 컷의 원본 사진" htmlFor="rf-source-photo"><select id="rf-source-photo" disabled={locked || done} value={run.referenceImages.some(image => image.id === reelSourceImageId(scene)) ? reelSourceImageId(scene) : ""} onChange={e => { if (e.target.value) void call({ action: "attach", sceneId: selected, assetId: e.target.value }); }}><option value="" disabled>업로드 원본 선택</option>{run.referenceImages.map((image, i) => <option key={image.id} value={image.id}>{i + 1}. {image.name}</option>)}</select></Field>}{reelSourceImageId(scene) && <div className="rf-source-preview"><img src={assetUrl(reelSourceImageId(scene)!)} alt="이 컷 영상의 시작 원본" /><small>이 사진의 피사체를 유지하며 움직임을 만듭니다. 생성한 영상과 원본은 각각 보관해요.</small></div>}<div className="rf-media-actions"><label className="rf-upload">이미지·영상 업로드<input type="file" accept="image/png,image/jpeg,image/webp,video/mp4,video/webm" disabled={locked || done} onChange={e => { const f = e.target.files?.[0]; if (f) void upload(f); e.target.value = ""; }} /></label><Button size="sm" disabled={locked || done} onClick={() => { setLibrary(v => !v); void api<Asset[]>("assets").then(setAssets); }}>내 라이브러리</Button></div>{library && <div className="rf-library">{assets.filter(a => /^(image|video)\//.test(a.mime)).map(a => <button type="button" key={a.id} disabled={locked || done} onClick={() => { void call({ action: "attach", sceneId: selected, assetId: a.id }); setLibrary(false); }}>{a.mime.startsWith("image") && <img src={a.url} alt="" />}<span>{a.name}</span></button>)}{!assets.length && <p>업로드한 파일이 없습니다.</p>}</div>}
      <Button disabled={locked || done || !quoteReady || !run.planApproved || !run.sampleApproved && selected !== run.scenes[0]?.id} onClick={() => void call({ action: "visual", kind: "image", sceneId: selected, credits: quote.image })}>장면 이미지 {scene.asset ? "다시 " : ""}생성 · {quoteReady ? `${quote.image} 크레딧` : "비용 확인 중"}</Button><Button disabled={locked || done || !quoteReady || !run.planApproved || draft.prompt !== scene.prompt || !run.sampleApproved && selected !== run.scenes[0]?.id} onClick={() => void call({ action: "visual", kind: "video", sceneId: selected, credits: quote.video })}>{reelSourceImageId(scene) ? "이 사진으로 영상 생성" : "장면 영상 생성"} · {quoteReady ? `${quote.video} 크레딧` : "비용 확인 중"}</Button>{draft.prompt !== scene.prompt && <small>변경한 컷 프롬프트를 먼저 저장해 주세요.</small>}<small>이미지는 부드러운 모션으로 합성됩니다. 영상 생성은 잔액 50 초과일 때 이용할 수 있어요.</small>
      {run.task?.state === "unknown" && ["image", "video"].includes(run.task.kind) && <Button onClick={() => void call({ action: "visual_status" })}>접수된 생성 상태 다시 확인</Button>}
      {run.task?.state === "unknown" && run.task.kind === "voice" && run.task.sceneId === selected && <div className="rf-question"><p>이전 음성 요청의 결과를 보관하지 못했습니다. 이전 결제는 확인 대상으로 유지되며, 새로 요청하면 {quote.voice} 크레딧이 추가로 사용됩니다.</p><Button disabled={locked || done} onClick={() => void call({ action: "voice", sceneId: selected, credits: quote.voice, acknowledgeUnknown: true })}>추가 비용 확인 · 음성 새로 요청</Button></div>}
      {run.spec.narration && <div className="rf-voice"><h4>AI 음성 · 실제 발화 자막</h4>{scene.voice && <><audio controls src={assetUrl(scene.voice.assetId)} /><small>실측 {(scene.voice.durationMs / 1000).toFixed(2)}초 · {scene.voice.matches ? "대본·전사 일치" : "대본·전사 차이 확인 필요"}</small><details><summary>실제 전사와 자막 시간</summary><p>{scene.voice.transcript}</p>{scene.voice.cues.map(c => <p key={c.id}>{(c.startMs / 1000).toFixed(2)}–{(c.endMs / 1000).toFixed(2)}초 {c.text}</p>)}</details></>}{scene.voice && !scene.voice.cues.length && <Button disabled={locked || done} onClick={() => void call({ action: "align", sceneId: selected })}>보관한 음성으로 자막 정렬 재시도</Button>}<Button disabled={locked || done || !quoteReady || !run.planApproved || !run.sampleApproved && selected !== run.scenes[0]?.id} onClick={() => void call({ action: "voice", sceneId: selected, credits: quote.voice })}>{scene.voice ? "음성 다시 만들기" : "음성·자막 만들기"} · {quoteReady ? `${quote.voice} 크레딧` : "비용 확인 중"}</Button></div>}
      </div>
      {!done && run.planApproved && <div className="rf-feedback"><Field label="이 구간에 의견 남기기" htmlFor="rf-feedback"><Textarea id="rf-feedback" value={feedback} maxLength={1500} rows={3} onChange={e => setFeedback(e.target.value)} placeholder="예: 첫 장면의 훅을 더 선명하게. 문구가 잠겨 있으면 먼저 변경을 허용해 주세요." /></Field><Button disabled={locked || feedback.length < 2} onClick={() => void call({ action: "revise", sceneIds: [selected], feedback })}>이 장면만 AI로 수정</Button></div>}
      </> : <p className="ws-muted">콘티가 준비되면 장면을 선택해 수정할 수 있어요.</p>}</aside>
    </div>
    {!!timeline.length && <section className="rf-timeline" aria-label="숏폼 시간축"><div className="rf-section-heading"><h3>시간으로 보는 콘티</h3><span>{run.scenes.filter(s => s.asset).length}/{run.scenes.length}장면 자산 · 총 {(timeline.at(-1)!.end / 30).toFixed(1)}초</span></div><div className="rf-scene-track">{timeline.map((s, i) => <button key={s.id} type="button" className={s.id === selected ? "is-selected" : ""} aria-pressed={s.id === selected} onClick={() => { setSelected(s.id); if (video.current && view?.kind === "full") video.current.currentTime = s.start / 30; }}><span className="rf-scene-thumb">{s.asset?.kind === "image" ? <img src={assetUrl(s.asset.id)} alt="" /> : <span>{s.asset?.kind === "video" ? "▶" : String(i + 1).padStart(2, "0")}</span>}</span><span><small>{time(s.start / 30)}—{time(s.end / 30)}</small><strong>{s.title}</strong><em>{roleLabel(s.role)} · {s.copyLocked ? "문구 보호" : "문구 변경 가능"}</em></span></button>)}</div>{run.spec.narration && <div className="rf-audio-track"><span>발화 / 자막</span>{timeline.map(s => <span key={s.id}>{s.voice ? `${(s.voice.durationMs / 1000).toFixed(1)}초 · ${s.voice.cues.length}구간` : "음성 대기"}</span>)}</div>}
      {run.planApproved && !done && <details className="rf-timeline-options"><summary>시간 재배분과 음악</summary><p>대본과 음성 원본을 유지하고 실제 발화 길이에 맞춰 시간을 배분합니다.</p><Button disabled={locked} onClick={() => void call({ action: "retime" })}>목표 길이 안에서 재배분</Button><Button disabled={locked} onClick={() => void call({ action: "retime", unlockDuration: true })}>길이 변경 허용 후 재배분</Button><div className="rf-music"><label className="rf-upload">배경음 업로드<input type="file" accept="audio/mpeg,audio/wav,audio/ogg,audio/mp4" disabled={locked} onChange={e => { const f = e.target.files?.[0]; if (f) void upload(f, true); e.target.value = ""; }} /></label><span>{run.music?.name || "음악 없음"}</span>{run.music && <Button size="sm" disabled={locked} onClick={() => void call({ action: "music" })}>음악 제거</Button>}</div><small>사용 권한이 있는 음악을 올려 주세요. 발화 중에는 음악을 낮춰 합성합니다.</small></details>}
    </section>}
    {run.planApproved && !done && issues.length > 0 && <section className="rf-checks"><h3>제작 전 확인</h3>{issues.map((i, n) => <button key={n} type="button" onClick={() => i.sceneId && setSelected(i.sceneId)}><span>{i.severity === "error" ? "필요" : "확인"}</span>{run.scenes.findIndex(s => s.id === i.sceneId) + 1 || "전체"}장면 · {i.message}</button>)}</section>}
    {!!run.reviews?.length && <details className="rf-history"><summary>출력 검수 기록 {run.reviews.length}개</summary>{run.reviews.map((q, i) => <div key={`${q.renderId}-${i}`}><strong>버전 {q.version} · {q.issues.filter(v => v.severity === "error").length ? "수정 필요" : "필수 오류 없음"}</strong><p>{q.summary}</p>{q.issues.map((v, n) => <p key={n}>{v.message}</p>)}</div>)}</details>}
    {run.output?.version === run.contentVersion && <section className="rf-quality"><div className="rf-section-heading"><div><span className="ws-eyebrow">REVIEW THE ACTUAL OUTPUT</span><h3>마지막은 실제 영상으로.</h3></div>{!done && <Button disabled={locked} onClick={() => void call({ action: "review" })}>실제 출력 프레임 AI 검수</Button>}</div><div className="rf-technical">{run.output.checks.map(c => <span key={c}>✓ {c}</span>)}</div><p className="ws-muted">AI는 장면별 대표 프레임을 검수합니다. 움직임 전체와 목소리는 정상 속도로 재생해 직접 확인해 주세요.</p>{currentQuality && <><p>{run.quality!.summary}</p>{run.quality!.issues.map((i, n) => <button className="rf-issue" key={n} type="button" onClick={() => i.sceneId && setSelected(i.sceneId)}><b>{i.severity === "error" ? "필수 수정" : "확인 권장"}</b> {i.message}</button>)}</>}
    {!done && currentQuality && <div className="rf-final-checks"><label><input type="checkbox" checked={watched} onChange={e => setWatched(e.target.checked)} /> 정상 속도로 전체 재생해 흐름·피사체·빈 구간을 확인했어요</label><label><input type="checkbox" checked={mutedChecked} onChange={e => setMutedChecked(e.target.checked)} /> 무음에서도 문구가 읽히고 핵심 내용이 전달돼요</label>{run.output.audio && <label><input type="checkbox" checked={listened} onChange={e => setListened(e.target.checked)} /> 발음·말끝·자막 싱크·음량을 듣고 확인했어요</label>}<Button variant="primary" disabled={locked || failedQuality || !watched || !mutedChecked || run.output.audio && !listened} onClick={() => void call({ action: "complete", watched, mutedChecked, listened })}>확인한 버전으로 완성 · 파일 보관</Button></div>}
    </section>}
    {run.artifacts && <section className="rf-delivery"><div><span className="ws-eyebrow">READY TO TAKE WITH YOU</span><h3>영상과 편집 자료를 보관했어요.</h3><p>내 라이브러리에서 다시 찾을 수 있어요.</p></div><a className="ohf-btn ohf-btn--primary" href={`/api/workspace/exports/${run.artifacts.zipId}`}><span className="ohf-btn-label">MP4·커버·편집 자료 ZIP</span></a><a href={`/api/workspace/exports/${run.artifacts.videoId}`}>MP4 다운로드</a><a href="/account/library">내 라이브러리</a></section>}
    {done && <div className="rf-followup">{run.planApproved && !!run.scenes.length && <Button disabled={busy} onClick={() => void start(run.id)}>현재 결과로 후속 제작 · 1 크레딧</Button>}<Button onClick={() => { setRun(null); window.history.replaceState(null, "", "/projects/new?format=reels"); }}>새 주제로 시작</Button></div>}
    {!!run.history.length && <details className="rf-history"><summary>이전 샘플·영상 {run.history.length}개</summary>{run.history.slice().reverse().map(h => <p key={h.id}><a href={assetUrl(h.assetId)} target="_blank" rel="noreferrer">{h.kind === "sample" ? "샘플" : "전체"} · v{h.version} · {h.duration}초</a> {h.version !== run.contentVersion && "이전 버전"}</p>)}</details>}
  </section>;
}
