import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { createDraft } from "../src/projects/outline";
import { parseProject, parseProductInfo } from "../src/projects/validation";
import { PRODUCT_EXAMPLES, PRODUCT_KINDS } from "../src/projects/product-detail";
import { landingHtml } from "../src/render/landing";
import { landingChecks, type LandingWorkflow } from "../src/projects/landing-workflow";
import { landingModelRequest, type LandingModel } from "../src/service/landing-model";
process.env.LOCAL_DATABASE_DIR = "memory://";
process.env.OPENAI_API_KEY = "sk-test-not-real";
process.env.OPENAI_OUTLINE_MODEL = "gpt-5.6-terra";
const { database } = await import("../src/service/db");
const { authenticate } = await import("../src/service/auth");
const { startLanding, activeLanding, getLanding, stepLanding, actLanding, parseLandingPlan } = await import("../src/service/landing-workflow");
const { getProject, updateProject, archiveProject } = await import("../src/service/projects");
const { getImageBoard, applyBoardImages } = await import("../src/service/landing-images");
const { saveAsset } = await import("../src/service/assets");
const { libraryList } = await import("../src/service/library");
const db = await database();
const user = (await authenticate({ email: "product@test.example", name: "Product QA", password: "testpass1234" }, true)).user;
const other = (await authenticate({ email: "other-product@test.example", name: "Other", password: "testpass1234" }, true)).user;
const product = { ...PRODUCT_EXAMPLES[0].product, shipping: "배송비 3,000원 · 결제 후 2일 내 출고", returns: "미사용 상품은 수령 후 7일 이내 접수" };
const act = (r: LandingWorkflow, data: Record<string, unknown>) => actLanding(user.id, r.id, { revision: r.revision, responseId: randomUUID(), ...data });
const provider: LandingModel = async r => r.stage === "understand" ? { summary: "구매 고객과 이유를 제안했습니다.", brand: "모닝", audience: "집에서 커피를 즐기는 사람", problem: "내 일상에 맞는 머그를 찾고 있음", value: "차분한 색상과 편안한 곡선", goal: "구매·상품 보기", ctaLabel: "구매하러 가기", traffic: "검색", explicit: ["audience"] } : r.stage === "plan" ? { summary: "상품 이해부터 구매 연결까지, 이미지 4장", sections: PRODUCT_KINDS.map(kind => ({ kind, title: `상품 ${kind}`, question: "구매 전에 무엇을 확인하나요?", message: "확정한 상품 정보로 설명", imagePlan: { enabled: ["hero", "features", "story", "usage"].includes(kind), ratio: kind === "hero" ? "1:1" : "16:9", description: `머그 ${kind} 장면` } })) } : r.stage === "review" ? { summary: "확정된 상품 정보와 원고를 대조했습니다.", issues: [] } : { title: "아침을 위한 머그", summary: "승인한 상품 흐름으로 작성", sections: (r.stage === "patch" ? r.project.slots.filter(s => s.id === r.targetId) : r.plan).map(s => ({ id: s.id, title: r.stage === "patch" ? "수정한 구매 포인트" : s.title, body: s.kind === "specs" ? product.specs : s.kind === "faq" ? "색상은 어떻게 고르나요?|아이보리와 차콜 중 골라 주세요." : "차분한 일상을 위한 머그를 소개합니다.", kicker: "MORNING", prompt: s.imagePlan?.enabled ? "Ceramic mug, natural light. No text, no logos." : "" })) };
const step = (r: LandingWorkflow) => stepLanding(user.id, r.id, r.revision, provider);
const start = () => startLanding(user.id, { format: "product-detail", product, idea: PRODUCT_EXAMPLES[0].idea, key: randomUUID() });

await test("product validation, manual draft, fixed information render and escaping", () => {
  const draft = createDraft("product-detail", { topic: product.name, audience: "커피를 즐기는 사람", tone: "calm", count: 8, mustInclude: "편안한 곡선" });
  draft.product = structuredClone(product);
  assert.deepEqual(parseProject(draft).product, product);
  assert.deepEqual(draft.slots.map(s => s.kind), PRODUCT_KINDS);
  const html = landingHtml(draft, {}, "/font.woff2", true);
  assert(html.includes('class="product-page"')); assert(html.includes("28,000원")); assert(html.includes("300 ml")); assert(html.includes(product.shipping));
  assert(html.includes("1200 × 1200")); assert(html.includes("생성 프롬프트")); assert(!landingHtml(draft).includes('class="image-placeholder"'));
  draft.product.price = '<script>alert(1)</script>'; draft.slots[0].href = 'javascript:alert(1)';
  const escaped = landingHtml(draft); assert(!escaped.includes("<script>")); assert(escaped.includes("&lt;script&gt;")); assert(!escaped.includes('href="javascript:'));
  assert.throws(() => parseProject(draft), /버튼 링크/);
  assert.throws(() => parseProductInfo({ ...product, specs: "x".repeat(1801) }), /규격/);
  assert.throws(() => parseProductInfo({}, true), /상품명/);
});

await test("product and landing workflow discovery, idempotency and refunds are isolated by format", async () => {
  const before = (await db.query<{credits:number}>("SELECT credits FROM users WHERE id=$1", [user.id]))[0].credits;
  const key = randomUUID();
  const [a,b] = await Promise.all([startLanding(user.id,{format:"product-detail",product,idea:"머그 소개",key}),startLanding(user.id,{format:"product-detail",product,idea:"머그 소개",key})]);
  assert.equal(a.id,b.id);
  const landing = await startLanding(user.id, { idea: "머그 브랜드 소개 페이지", key: randomUUID() });
  assert.equal((await activeLanding(user.id))?.id, landing.id);
  assert.equal((await activeLanding(user.id,"product-detail"))?.id, a.id);
  await assert.rejects(startLanding(user.id,{idea:"다른 형식",key}), /다른 형식/);
  await assert.rejects(getLanding(other.id,a.id), /찾을 수 없습니다/);
  await archiveProject(user.id,a.projectId); await archiveProject(user.id,landing.projectId);
  assert.equal(await activeLanding(user.id,"product-detail"),null);
  assert.equal((await db.query<{credits:number}>("SELECT credits FROM users WHERE id=$1", [user.id]))[0].credits,before);
});

await test("product intent, plan, copy, scoped revision, approved images, handoff, and library persistence", async () => {
  let r = await step(await start());
  assert.deepEqual(r.intent.product, product);
  r = await act(r, { action: "confirm_intent", intent: { ...r.intent, product, ctaHref: "https://example.com/products/mug" } });
  const request = landingModelRequest(r); assert(request.instructions.includes("제품 상세")); assert(request.instructions.includes("PRODUCT_KINDS") === false);
  assert(JSON.stringify(request.text.format.schema).includes('"specs"')); assert(request.input.includes(product.price)); assert(JSON.parse(request.input).displayedProduct);
  r = await step(r);
  assert.throws(() => parseLandingPlan(r.plan), /역할/);
  assert.equal(parseLandingPlan(r.plan, r.plan, "product-detail").length, 8);
  r = await act(r, { action: "confirm_plan", plan: r.plan });
  r = await step(r); r = await step(r); assert.equal(r.status,"ready");
  const previous = structuredClone(r.project.slots);
  r = await act(r,{action:"revise",sectionId:r.project.slots[1].id,feedback:"구매 이유를 더 구체적으로"});
  r = await step(r); r = await step(r);
  assert.deepEqual(r.project.product,product);
  assert.deepEqual(r.project.slots.filter((_,i)=>i!==1),previous.filter((_,i)=>i!==1));
  let board = await getImageBoard(user.id,r.projectId); assert.equal(board.items.length,4); assert.equal(board.items[0].plan.ratio,"1:1");
  await assert.rejects(getImageBoard(other.id,r.projectId), /찾을 수 없습니다/);
  const asset = await saveAsset(user.id,new File([Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a7YsAAAAASUVORK5CYII=","base64")],"product.png",{type:"image/png"}),true);
  await db.query("UPDATE assets SET project_id=$1 WHERE id=$2",[r.projectId,asset.id]);
  board.items[0].candidate={kind:"image",url:asset.url};board.items[0].state="completed";board.items[0].applied=false;board.items[0].jobId="qa-image";
  await db.query("UPDATE project_image_boards SET data=$1 WHERE project_id=$2",[JSON.stringify(board),r.projectId]);
  const applied=await applyBoardImages(user.id,r.projectId,{revision:board.revision});
  assert.equal(applied.project.slots[0].media?.url,asset.url);
  r=await getLanding(user.id,r.id);assert.deepEqual(r.project.product,product);assert.equal(r.review?.version,r.contentVersion);
  assert(landingChecks(r).some(i=>i.message.includes("실제 판매 상품")));
  const { adminList } = await import("../src/service/admin-reports");
  await assert.rejects(adminList(other.id,"projects",{feature:"product-detail"}), /관리자/);
  await db.query("UPDATE users SET is_admin=TRUE WHERE id=$1",[user.id]);
  assert((await adminList(user.id,"projects",{feature:"product-detail"})).items.some(p=>p.id===r.projectId));
  assert((await adminList(user.id,"activity",{feature:"product-detail"})).items.some(j=>j.project_id===r.projectId));
  const result=await libraryList(user.id,{feature:"product-detail"});assert.equal(result.total,1);assert.equal(result.items[0].projectId,r.projectId);
  r=await act(r,{action:"handoff",acknowledged:true});assert.equal(await activeLanding(user.id,"product-detail"),null);
  const saved=await getProject(user.id,r.projectId);assert.deepEqual(saved.product,product);
  const updated=await updateProject(user.id,saved.id,{...saved,product:{...product,price:"30,000원"}});assert.equal(updated.product?.price,"30,000원");
  assert(landingHtml(updated).includes("30,000원"));
});
