import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import sharp from "sharp";
import type { ReelWorkflow } from "../src/projects/reel-workflow";
import { reelSourceImageId } from "../src/projects/reel-workflow";
import { reelRecommendedPrompt } from "../src/projects/reel-recommendation";
import { createPlatformClient, providerStorageUrl } from "../src/generation/platform";
import { toPlatform } from "../src/generation/to-platform";
process.env.LOCAL_DATABASE_DIR = "memory://";
process.env.OPENAI_API_KEY = "sk-reel-images-fixture";
process.env.OPENAI_OUTLINE_MODEL = "gpt-5.6-terra";
const { database } = await import("../src/service/db");
const { authenticate } = await import("../src/service/auth");
const { uploadProductImage, productVisionImages } = await import("../src/service/product-images");
const { startReel, getReel, actReel, stepReel, parseReelScenes } = await import("../src/service/reel-workflow");
const { reelModelRequest } = await import("../src/service/reel-model");
const { reelPlane, reelQuote, generateReelVisual, pollReelVisual, attachReelAsset } = await import("../src/service/reel-media");
const { reelSourceFrame } = await import("../src/service/reel-source");
const { recommendReel, parseReelRecommendation, reelRecommendationModel, reelRecommendationRequest } = await import("../src/service/reel-recommendation");
const { assetFile } = await import("../src/service/assets");
const db = await database();
const user = (await authenticate({ email: "reel-images@test.example", name: "Photo reel", password: "fixture12345" }, true)).user;
const other = (await authenticate({ email: "reel-foreign@test.example", name: "Other", password: "fixture12345" }, true)).user;
await db.query("UPDATE users SET credits=500 WHERE id=$1", [user.id]);
const bytes = await sharp({create:{width:120,height:80,channels:3,background:"#aabc99"}}).png().toBuffer();
const photo = await uploadProductImage(user.id, new File([new Uint8Array(bytes)], "scene.png", {type:"image/png"}));
const second = await uploadProductImage(user.id, new File([new Uint8Array(bytes)], "detail.png", {type:"image/png"}));
const foreign = await uploadProductImage(other.id, new File([new Uint8Array(bytes)], "foreign.png", {type:"image/png"}));
const balance = async () => (await db.query<{credits:number}>("SELECT credits FROM users WHERE id=$1",[user.id]))[0].credits;
const act = (r:ReelWorkflow, data:Record<string,unknown>)=>actReel(user.id,r.id,{revision:r.revision,responseId:randomUUID(),...data});
let run: ReelWorkflow;
await test("photo-only start stores owned references; invalid selections never reserve credits", async()=>{
  const before=await balance();
  for(const ids of [[foreign.id],[photo.id,photo.id],[randomUUID()],Array(7).fill(photo.id)]) await assert.rejects(startReel(user.id,{key:randomUUID(),referenceImageIds:ids}));
  await assert.rejects(startReel(user.id,{key:randomUUID(),idea:"",referenceImageIds:[]}));
  assert.equal(await balance(),before);
  run=await startReel(user.id,{key:randomUUID(),referenceImageIds:[photo.id,second.id],duration:15});
  assert.equal(await balance(),before-1); assert.equal(run.referenceImages?.length,2); assert.ok(run.idea.includes("사진"));
  assert.deepEqual((await getReel(user.id,run.id)).referenceImages,run.referenceImages);
  await assert.rejects(getReel(other.id,run.id));
});
await test("multimodal planning maps each cut to owned source and keeps original on scoped copy edits",async()=>{
  const images=await productVisionImages(user.id,run.referenceImages!);
  const request=reelModelRequest(run,images);
  assert.equal(typeof request.input,"object"); assert.ok(JSON.stringify(request.input).includes("data:image/jpeg;base64,"));
  run=await stepReel(user.id,run.id,run.revision,async(_r,owner)=>{assert.equal(owner,user.id);return{value:{summary:"写真 fixture",purpose:"branding",purposeExplicit:true,audience:"휴식을 찾는 사람",constraints:[],needResearch:false}}});
  const scenes=[photo,second,photo].map((image,i)=>({id:`scene-${i+1}`,sourceImageId:image.id,role:i?"development":"hook",title:`컷 ${i+1}`,screenText:"차분한 순간",narration:"",prompt:"Slow cinematic push in. Preserve the scene.",seconds:5}));
  assert.throws(()=>parseReelScenes([{...scenes[0],sourceImageId:foreign.id}],run),/업로드한 사진/);
  run=await stepReel(user.id,run.id,run.revision,async()=>({value:{summary:"사진 컷",title:"사진에서 시작한 릴스",caption:"여유",scenes}}));
  assert.equal(run.stage,"review");
  run=await stepReel(user.id,run.id,run.revision,async()=>({value:{summary:"원본과 컷 일치",issues:[]}}));
  assert.equal(run.question?.kind,"plan"); assert.deepEqual(run.scenes.map(s=>s.asset?.id),[photo.id,second.id,photo.id]);
  assert.equal(run.project.slots[1].media?.url,photo.url.replace(photo.id,second.id));
  const patchRun=structuredClone(run);patchRun.targetIds=[run.scenes[0].id];patchRun.scenes[0].copyLocked=true;
  const patched=parseReelScenes([{...scenes[0],title:"변경 금지",sourceImageId:foreign.id}],patchRun,true);
  assert.equal(patched[0].sourceImageId,photo.id);assert.equal(patched[0].title,run.scenes[0].title);
  run=await act(run,{action:"answer",requestId:run.question!.id});
  run=await attachReelAsset(user.id,run.id,{revision:run.revision,sceneId:run.scenes[0].id,assetId:second.id});
  assert.equal(run.scenes[0].sourceImageId,second.id);
});
await test("image-derived frame preserves stored source bytes and supplies a portrait start image",async()=>{
  const frame=await reelSourceFrame(user.id,photo.id),meta=await sharp(frame).metadata();assert.equal(meta.width,720);assert.equal(meta.height,1280);
  assert.deepEqual(Buffer.from((await assetFile(user.id,photo.id)).data!),bytes);
  await assert.rejects(reelSourceFrame(other.id,photo.id));
  const plane=reelPlane(run,run.scenes[0],"video","https://cdn.higgsfield.ai/source.jpg");
  assert.equal(plane.model,"kling-3-turbo");const mapped=toPlatform(plane);assert.match(mapped.path,/image-to-video$/);assert.equal(mapped.body.image_url,"https://cdn.higgsfield.ai/source.jpg");
  const generated={...run.scenes[0],asset:{id:randomUUID(),name:"out.mp4",kind:"video" as const,width:720,height:1280,duration:5}};
  assert.equal(reelSourceImageId(generated),second.id);assert.equal(reelPlane(run,generated,"video").model,"kling-3-turbo");
});
await test("provider storage upload follows signed PUT contract without forwarding API authorization",async()=>{
  const calls:{url:string;init?:RequestInit}[]=[];
  const client=createPlatformClient({apiKey:"fixture-id:fixture-secret",baseUrl:"https://api.higgsfield.ai",fetch:async(input,init)=>{const url=String(input);calls.push({url,init});return url.includes("generate-upload-url")?Response.json({upload_url:"https://bucket.s3.amazonaws.com/put",public_url:"https://cdn.higgsfield.ai/source.jpg",upload_headers:{"Content-Type":"image/jpeg"}}):new Response(null,{status:200});}});
  assert.equal(await client.upload!(new Uint8Array([1,2,3]),"image/jpeg"),"https://cdn.higgsfield.ai/source.jpg");
  assert.match(new Headers(calls[0].init?.headers).get("Authorization")!,/^Key /);
  assert.equal(new Headers(calls[1].init?.headers).get("Authorization"),null);assert.equal(calls[1].init?.method,"PUT");assert.equal(calls[1].init?.redirect,"error");
  for(const url of ["http://cdn.higgsfield.ai/a","https://127.0.0.1/a","https://higgsfield.ai.evil.test/a","https://user:pass@cdn.higgsfield.ai/a"])assert.throws(()=>providerStorageUrl(url));
});
await test("I2V submits one owned image and one charge; replay and low balance do not upload again",async()=>{
  let uploads=0,submits=0;let body:Record<string,unknown>={};
  const client={upload:async(frame:Uint8Array)=>{uploads++;assert.equal((await sharp(frame).metadata()).height,1280);return "https://cdn.higgsfield.ai/source.jpg"},submit:async(path:string,input:Record<string,unknown>)=>{submits++;assert.match(path,/image-to-video$/);body=input;return {requestId:"photo-video-1",status:"queued",statusUrl:"",cancelUrl:""}},status:async()=>({requestId:"photo-video-1",status:"pending"})};
  const cost=await reelQuote(user.id,run.id,run.scenes[0].id), before=await balance();
  const data={revision:run.revision,responseId:randomUUID(),sceneId:run.scenes[0].id,kind:"video",credits:cost.video};
  run=await generateReelVisual(user.id,run.id,data,client);assert.equal(body.image_url,"https://cdn.higgsfield.ai/source.jpg");
  assert.equal(run.status,"waiting_tool");assert.equal(await balance(),before-cost.video);
  await generateReelVisual(user.id,run.id,data,client);assert.equal(uploads,1);assert.equal(submits,1);
  run=await pollReelVisual(user.id,run.id,{...client,status:async()=>({requestId:"photo-video-1",status:"failed",error:"fixture rejected"})});
  assert.equal(await balance(),before);
  await db.query("UPDATE users SET credits=50 WHERE id=$1",[user.id]);
  await assert.rejects(generateReelVisual(user.id,run.id,{...data,revision:run.revision,responseId:randomUUID()},client),/50/);assert.equal(uploads,1);assert.equal(submits,1);
  run=await act(run,{action:"cancel"});
});
const recommendation={idea:"사진 속 초록 공간의 분위기를 차분하게 보여 주세요. 가격·구매 유도 제외.",shots:[{sourceImageId:photo.id,title:"초록으로 시작",motion:"천천히 다가가기"},{sourceImageId:second.id,title:"디테일",motion:"부드럽게 옆으로 이동"}],observations:["차분한 초록색"],uncertainties:["구체적인 식물 종류는 확인 필요"]};
await test("photo recommendation accepts empty text and returns grounded editable prompts without credits",async()=>{
  const before=await balance();const result=await recommendReel(user.id,{referenceImageIds:[photo.id,second.id],idea:"",duration:15},async(images,context)=>{assert.equal(images.length,2);assert.equal(context.idea,"");return recommendation});
  assert.equal(await balance(),before);const prompt=reelRecommendedPrompt(result,[photo,second]);assert.ok(prompt.length<3000);assert.match(prompt,/사진 2/);
  assert.throws(()=>parseReelRecommendation({...recommendation,shots:[{...recommendation.shots[0],sourceImageId:foreign.id}]},[photo.id]),/연결/);
  assert.throws(()=>parseReelRecommendation({...recommendation,shots:[recommendation.shots[0]]},[photo.id,second.id]),/연결/);
  await assert.rejects(recommendReel(other.id,{referenceImageIds:[photo.id]}));
  await assert.rejects(recommendReel(user.id,{referenceImageIds:[]}));
  await assert.rejects(recommendReel(user.id,{referenceImageIds:[photo.id],duration:99}));
});
await test("recommendation transport includes images, model and output schema; incomplete response never applies",async()=>{
  const images=[{id:photo.id,imageUrl:"data:image/jpeg;base64,AAA="}],context={idea:"",duration:15,narration:false};
  const request=reelRecommendationRequest("gpt-5.6-terra","low",images,context);assert.deepEqual(request.reasoning,{effort:"low"});assert.ok(JSON.stringify(request.input).includes(images[0].imageUrl));assert.equal(request.text.format.strict,true);
  await assert.rejects(reelRecommendationModel(images,context,async()=>Response.json({status:"incomplete",output:[]})),/완성/);
  await assert.rejects(reelRecommendationModel(images,context,async()=>new Response(null,{status:401})),/HTTP 401/);
});
await test("one photo can seed every cut and failed input upload never becomes a text-only video",async()=>{
  let r=await startReel(user.id,{key:randomUUID(),referenceImageIds:[photo.id],duration:15});
  const scenes=[1,2,3].map(i=>({id:`scene-${i}`,sourceImageId:photo.id,role:"hook",title:`사진 컷 ${i}`,screenText:"",narration:"",prompt:"A calm slow camera move.",seconds:5}));
  assert.deepEqual(parseReelScenes(scenes,r).map(s=>s.asset?.id),[photo.id,photo.id,photo.id]);
  r=await stepReel(user.id,r.id,r.revision,async()=>({value:{summary:"방향",purpose:"branding",purposeExplicit:true,audience:"",constraints:[],needResearch:false}}));
  r=await stepReel(user.id,r.id,r.revision,async()=>({value:{summary:"한 장에서 세 컷",title:"사진 릴스",caption:"",scenes}}));
  r=await stepReel(user.id,r.id,r.revision,async()=>({value:{summary:"원본과 컷 일치",issues:[]}}));
  r=await act(r,{action:"answer",requestId:r.question!.id});
  await db.query("UPDATE users SET credits=500 WHERE id=$1",[user.id]);
  const before=await balance();let submits=0;
  const cost=await reelQuote(user.id,r.id,r.scenes[0].id);
  r=await generateReelVisual(user.id,r.id,{revision:r.revision,responseId:randomUUID(),sceneId:r.scenes[0].id,kind:"video",credits:cost.video},{upload:async()=>{throw new Error("fixture storage outage")},submit:async()=>{submits++;throw new Error("must not submit")},status:async()=>({requestId:"",status:"pending"})});
  assert.equal(submits,0);assert.equal(await balance(),before);assert.equal(r.task?.state,"failed");assert.equal(r.scenes[0].sourceImageId,photo.id);assert.match(r.error!,/사진을 전달하지/);
  await act(r,{action:"cancel"});
});
