import type { ProductInfo } from "@/projects/product-detail";
// Output uses the selected design preset's colors and typography from landingHtml.
export const productCss = `
.product-page header>a{white-space:nowrap;flex-shrink:0}.product-page .hero{grid-template-columns:1fr 1fr;min-height:620px;gap:56px}.product-page .hero>div{order:2}.product-page .hero>img,.product-page .hero>figure{order:1}.product-page .hero>img{object-fit:contain;max-height:600px}.product-page .hero:not(:has(img)){display:block}.product-page .hero h1{font-size:clamp(32px,4vw,54px)}.product-page .product-tagline{font-weight:650;font-size:20px;opacity:1}.product-price{font-size:28px;font-weight:750;margin:26px 0 12px;opacity:1;font-variant-numeric:tabular-nums}.product-options{display:flex;flex-wrap:wrap;gap:12px;border-block:1px solid var(--product-rule);padding:16px 0;margin:18px 0;font-size:14px;white-space:pre-line}.product-options>span{opacity:.7}.product-options>strong{font-weight:500;overflow-wrap:anywhere}.product-specs{display:grid;margin:28px 0;grid-template-columns:minmax(90px,1fr) 2fr}.product-specs dt,.product-specs dd{margin:0;padding:18px 12px;border-bottom:1px solid var(--product-rule);white-space:pre-line;overflow-wrap:anywhere}.product-specs dt{font-weight:650}.product-policies{display:grid;grid-template-columns:1fr 1fr;gap:40px}.product-page .usage{display:grid;grid-template-columns:1fr 1fr;gap:48px;align-items:center}.product-page .specs>img,.product-page .shipping>img{margin-top:32px}.product-page .hero:has(.image-placeholder){grid-template-columns:1fr 1fr}.product-page .product-specs~.image-placeholder{margin-top:32px}@media(max-width:700px){.product-page .hero,.product-page .hero:has(.image-placeholder),.product-page .usage,.product-policies{grid-template-columns:1fr;gap:24px}.product-page .hero>div{order:2}.product-page .hero{min-height:auto}.product-page .hero>img{max-height:none}.product-specs dt,.product-specs dd{padding:16px 8px}.product-price{font-size:24px}}
`;
export function productSummary(p: ProductInfo | undefined, e: (s: string) => string) {
  if (!p) return "";
  return `${p.price ? `<p class="product-price">${e(p.price)}</p>` : ""}${p.options ? `<div class="product-options"><span>옵션·구성</span><strong>${e(p.options)}</strong></div>` : ""}`;
}
export function productSpecs(value: string, e: (s: string) => string) {
  return `<dl class="product-specs">${value.split("\n").filter(Boolean).map(line => { const [label, ...detail] = line.split("|"); return detail.length ? `<dt>${e(label)}</dt><dd>${e(detail.join("|"))}</dd>` : `<dt>상품 정보</dt><dd>${e(line)}</dd>`; }).join("")}</dl>`;
}
